ncats/gsrs-spring-module-substances

- gsrs-module-substance-example/src/test/java/example/substance/datasearch/UpdateUserDoesntAffectSearchTest.java
These tests currently fail but will pass once https://github.com/ncats/gsrs-spring-starter/pull/46 is merged.
> tests to make sure user updates don't break Searches

- gsrs-module-substance-example/src/test/java/example/substance/validation/DuplicateChemicalStructureFinderTest.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/ChemicalDuplicateFinder.java
- runTests.sh
changed Duplicate check to chunk the search by keyword so we don't go over the SQL IN size limit.
Also added more tests to make sure the chunking worked and cleaned the code up a bit.
> changed Duplicate check to chunk the search by keyword

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceController.java
Add explicit TypedCallable annotation for caching the bytes in a rendered image. This will give hints to the cache about the eviction policy, which is useful in preventing some deadlock issues.
> updated renderer to add explicit typed callable

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/services/SubstanceSequenceSearchService.java
Add sequence type to the cache key to prevent bad cache results.
> Seq cache fix

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/exporters/DefaultSubstanceSpreadsheetExporterFactory.java
Doing this allows the _full_ entity to be fetched for use in export, rather than just the limited lazy loaded view that hibernate will typically get. Without this it will error out when trying to fetch codes _unless_ specific elements are requested while the transaction is open.
> use entityfetcher for parent, instead of repo

- gsrs-module-substance-example/src/test/java/example/substance/indexer/BracketTermIndexValueMakerTest.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/indexers/BracketTermIndexValueMaker.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Name.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/ValidationUtils.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/NamesValidator.java
- gsrs-module-substances-dto/pom.xml
- gsrs-module-substances-tests/pom.xml
Note extract locators is turned off
> WIP: Update the BracketTermIndexValueMaker and extractLocators to use the tag utilities class (GSRS-2467)

- gsrs-module-substance-example/src/test/java/example/prot/ProtCalculationTest.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/ProteinUtils.java
(https://cnigsllc.atlassian.net/browse/GSRS-2503)
> Support for lowercase amino acid codes in mol formula calculation

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceController.java
> allow facets to be pulled from flex searches

- gsrs-module-substances-core/src/main/java/ix/core/models/XRef.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Code.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Name.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Reference.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Relationship.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Substance.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/SubstanceReference.java
Creating indexes during database initialization, this is one set of modifications. The other set of modifications are in starter project.
> Add table indexes 2084

- .gitignore
- gsrs-fda-substance-extension/pom.xml
- gsrs-module-substance-example/pom.xml
- gsrs-module-substances-api/pom.xml
- gsrs-module-substances-core/pom.xml
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/repository/NameRepository.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/tasks/NameStandardizerTaskInitializer.java
- gsrs-module-substances-dto/pom.xml
- gsrs-module-substances-spring-boot-autoconfigure/pom.xml
- gsrs-module-substances-spring-boot-starter/pom.xml
- gsrs-module-substances-tests/pom.xml
- pom.xml
This addresses https://cnigsllc.atlassian.net/browse/GSRS-2487
> Namestdtask

- gsrs-module-substances-core/src/main/java/ix/core/chem/Chem.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/CVFragmentStructureValidator.java
Another pull request is in starter.
> Cv validator 2613

- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/CVFragmentStructureValidator.java
> filter type before cast

- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/NamesValidator.java
Returning master branch to the way it was earlier
> undid previous change.

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceController.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/SubstanceFieldNameDecorator.java
- gsrs-module-substances-core/src/main/resources/substances-core.conf
Improve identifier management for default searches.
> enhance support for identifier searches

- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/QualifiedAtom.java
Updated QualifiedAtom to include exact mass necessary for configurable molecular weight calculations
> Updated QualifiedAtom 

- gsrs-module-substance-example/src/test/java/example/substance/SubstanceRepoRetrieveTest.java
- gsrs-module-substance-example/src/test/resources/application-test.conf
- gsrs-module-substances-core/pom.xml
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceLegacyBulkLoadController.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/repository/SubstanceRepository.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/services/SubstanceBulkLoadService.java
- gsrs-module-substances-core/src/main/java/ix/core/models/ProcessingJob.java
This pull request fixes some errors that prevented import of multi-record GSRS JSON files when the backing database was MariaDB.
> Data load mariadb

- gsrs-module-substance-example/src/main/java/example/GsrsModuleSubstanceApplication.java
This adds a more update configuration to substance example consistent with Egor's  changes in spring_update_branch
> sm change api config in substance example

- gsrs-module-substance-example/src/test/java/example/substance/validation/ChemicalValidatorTest.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/ChemicalValidator.java
- gsrs-module-substances-core/src/main/resources/substances-core.conf
Made the change to the ChemicalValidator and created a unit test
> Implemented https://cnigsllc.atlassian.net/browse/GSRS-2704

- gsrs-module-substances-core/src/main/java/ix/ginas/utils/CodeSystemGenerator.java
This PR will fix exception if CodeSystemGenerator used as ApprovalIdGenerator.
> fix exception if CodeSystemGenerator used as ApprovalIdGenerator

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/exporters/DefaultSubstanceSpreadsheetExporterFactory.java
> fix for NPE on line 11- check of ster

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceController.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/services/LegacySubstanceSequenceSearchService.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/services/SubstanceStructureSearchService.java
- gsrs-module-substances-core/src/main/java/ix/core/chem/InchiStandardizer.java
There's another PR for starter for this too
> Fix keys to fix the highlighting of atoms

- gsrs-module-substance-example/src/test/java/example/exports/scrubbers/BasicSubstanceScrubberTests.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/scrubbers/basic/BasicSubstanceScrubber.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Name.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Substance.java
- gsrs-module-substances-core/src/main/resources/substances-core.conf
Fix for issue where display names are absent from export of delimited data, PUBLIC_ONLY.
Credit: Tyler
> Export name fix

- gsrs-module-substances-core/src/main/resources/schemas/scrubberSchema.json
> tweak to comments in schema

- gsrs-module-substances-core/src/main/java/ix/core/models/Structure.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Code.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Moiety.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Name.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/NameOrg.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Note.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Property.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Reference.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Relationship.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/Substance.java
This PR will create a foreign key indexes on PostgreSQL (Oracle) databases. It fixes the #130 Issue.
> force creation of the foreign key indexes

- gsrs-module-substance-example/src/test/java/example/substance/ssg1/SpecifiedSubstanceGroup1SubstanceTest.java
- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/SpecifiedSubstanceGroup1Substance.java
https://cnigsllc.atlassian.net/browse/GSRS-2804
> Fix for NPE that occurs when export SSG1 with scrubbed definition.

- gsrs-module-substance-example/src/test/java/example/name/NameUtilitiesTest.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/NameUtilities.java
> WIP: handle greater than, and less than, and and amperstand in name in html cleanup for std name

- gsrs-fda-substance-extension/src/main/java/fda/gsrs/substance/exporters/FDARelationshipExporter.java
- gsrs-fda-substance-extension/src/main/java/fda/gsrs/substance/exporters/FDARelationshipExporterFactory.java
Remove this from "ix.ginas.export.factories.substances" array config  
"fda.gsrs.substance.exporters.FDARelationshipExporterFactory" 
Then add this to the configuration.  (The default for includeBdnum is false) 
For fda we need to set the configuration with include bdnum equal to true. 
```
ix.ginas.export.exporterfactories.substances +=
{
"exporterFactoryClass" : "fda.gsrs.substance.exporters.FDARelationshipExporterFactory",
"parameters":{
"includeBdnum": true
}
}
```
> WIP: sm clean up relationship report code, make configurable

- gsrs-module-substance-example/src/test/java/example/name/NameUtilitiesTest.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/NameUtilities.java
replace &NBSP with regular space.
> WIP: Remove nbsp

- gsrs-module-substance-example/src/test/java/example/substance/ImageUtilitiesTest.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/ImageUtilities.java
Addresses the issue found by Archana on FDA dev server
> Retrieve image data directly from payloadservice rather than via http

- .gitignore
- gsrs-module-substance-example/pom.xml
- gsrs-module-substance-example/src/test/java/example/imports/DelimTextAdapterFactoryTest.java
- gsrs-module-substance-example/src/test/java/example/substance/ImageUtilitiesTest.java
- gsrs-module-substances-core/pom.xml
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceController.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/importers/SDFImportAdapterFactory.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/importers/importActionFactories/SubstanceImportAdapterFactoryBase.java
- gsrs-module-substances-data-exchange/src/main/java/gsrs/data_exchange/processors/CalculateMatchablesProcessor.java
- gsrs-module-substances-data-exchange/src/main/java/gsrs/data_exchange/tasks/CalculateMatchablesScheduledTask.java
- gsrs-module-substances-dto/pom.xml
- gsrs-module-substances-tests/pom.xml
To enable testing on project server
> New xfer tests

- gsrs-module-substance-example/src/test/java/example/imports/GSRSJSONImportAdapterFactoryTest.java
- gsrs-module-substance-example/src/test/resources/application-test.conf
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/importers/GSRSJSONImportAdapter.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/importers/GSRSJSONImportAdapterFactory.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/indexers/SubstanceDefinitionalHashIndexer.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/processors/LegacyAuditInfoProcessor.java
- gsrs-module-substances-core/src/main/resources/substances-core.conf
- gsrs-module-substances-data-exchange/src/main/java/gsrs/dataexchange/processors/CalculateMatchablesProcessor.java
> WIP: Fix for DataIntegrityViolationException that occurred with

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/importers/importActionFactories/NoOpActionFactory.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/importers/importActionFactories/ReferenceExtractorActionFactory.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/importers/importActionFactories/SubstanceImportAdapterFactoryBase.java
> make sure file name is passed to new reference even when there's a

- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/ImageReferenceValidator.java
> Generate a warning when an image reference is added to a polymer or chemical

- gsrs-module-substances-data-exchange/src/main/java/gsrs/dataexchange/processors/CalculateMatchablesProcessor.java
appears to fix error changing substance type (and maybe additional errors)
> Simple proc1

- gsrs-module-substance-example/src/test/java/example/imports/SSG1GetSubstanceReferencesAndParentsBeyondDependsOnTests.java
- gsrs-module-substance-example/src/test/java/example/prot/ProtCalculationTest.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/tasks/SubstanceRefTaskInitializer.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/ProteinUtils.java
Addresses a formula calculation issue reported by a colleague at FDA
> Protein calc 2023

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/indexers/UserSavedListIndexValueMaker.java
Companion update to:
https://github.com/ncats/gsrs-spring-starter/pull/208
> WIP: allow partial indexing of user list

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/standardizer/HtmlNameStandardizer.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/HtmlUtil.java
This PR will fix truncation issue of the HTML Names with UTF-8 characters.
> Fix truncation of the HTML Names with UTF-8 characters

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/HtmlUtil.java
This PR will fix the truncation of the Names containing HTML special characters &,<,>.
> Fix Name truncation containing special HTML characters

- gsrs-module-substances-api/pom.xml
> fixed version

- gsrs-module-substance-example/pom.xml
- gsrs-module-substances-api/pom.xml
- gsrs-module-substances-core/pom.xml
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceController.java
- gsrs-module-substances-dto/pom.xml
- gsrs-module-substances-tests/pom.xml
- gsrs-ncats-substance-extension/pom.xml
Relies on:
https://github.com/ncats/molwitch-cdk/pull/19/
https://github.com/ncats/molwitch-renderer/pull/20
https://github.com/ncats/molwitch/pull/11
Fixes how rendering works for complex stereo.
> fix racemic stereo rendering

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/HtmlUtil.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/CodesValidator.java
This PR adds the codes comments HTML validation to the CodesValidator.
> code comments HTML validation

- gsrs-fda-substance-extension/src/main/java/fda/gsrs/substance/validators/BdNumModificationValidator.java
- gsrs-module-substances-core/src/main/java/ix/core/models/Structure.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/ChemUtils.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/GinasV1ProblemHandler.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/ProteinUtils.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/ValidationUtils.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/ChemicalValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/CodeFormatValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/DefinitionalHashValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/NamesValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/NucleicAcidValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/PolymerValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/PrimaryDefinitionValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/ProteinValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/StandardNameValidator.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/SubstanceUniquenessValidator.java
This PR Normalized the Validators Messages. The duplcated empty spaces and empty spaces at the end of the message will be removed. The Validation messages will be changed to support MessageId generation.
> Normalize the ValidationMassages texts

- gsrs-module-substance-example/src/test/java/example/substance/validation/SubstanceUniquenessValidatorTest.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/definitional/StructurallyDiverseDefinitionalElementImpl.java
> added 2 fields to the definitional hash of structurally diverse

- gsrs-module-substance-example/src/test/java/example/chem/SaltRemovalTest.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/controllers/SubstanceController.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/ChemicalUtils.java
prevents generation of an empty query molfile that gives runtime exceptions
> Fixes how we remove salt 

- gsrs-module-substances-core/pom.xml
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/SplitFunction.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/utils/UniqueFunction.java
- gsrs-module-substances-core/src/main/java/ix/ginas/utils/validation/validators/JmespathValidator.java
Addresses https://ncats-nih.atlassian.net/browse/NGSRS-419
> JmespathValidator from Egor

- gsrs-module-substances-core/src/main/java/gsrs/module/substance/exporters/GsrsApiExporter.java
- gsrs-module-substances-core/src/main/java/gsrs/module/substance/exporters/GsrsApiExporterFactory.java
> adding new exporter from Egor Puzanov

- gsrs-module-substances-core/src/main/java/ix/ginas/models/v1/DisulfideLink.java
to see effect on saving errors
> uncommented @Entity and @Table annotations and commented @IgnoredModel
